use sakila;
show tables;

#1.List the number of films per category.
select name, count(film_id)
from film_category as fc
inner join category as c
on fc.category_id=c.category_id
group by name;

#2. Retrieve the store ID, city, and country for each store.
select store_id, city, country
from customer as c
inner join address as a
on c.address_id=a.address_id
inner join city as ci
on a.city_id=ci.city_id
inner join country as co
on ci.country_id=co.country_id;

#3.Calculate the total revenue generated by each store in dollars.

select st.store_id, sum(amount)
from store as st
inner join staff as sta
on st.store_id=sta.store_id
inner join payment as p
on sta.staff_id=p.staff_id
group by store_id;

#4. Determine the average running time of films for each category.
select name, avg(length)
from film as f
inner join film_category as fa
on f.film_id=fa.film_id
inner join category as c
on fa.category_id=c.category_id
group by name;